### PR TITLE
feat: consider pagination when fetching notes from GitLab API

### PR DESCRIPTION
**Pull request by kitagry**
SSIA

### CODE REVIEW

**Comment by yuyaban** [comment]
Thanks! LGTM!

**Comment by yuyaban** [comment]
@kitagry 
Thanks! LGTM!

**Comment by yuyaban** [comment]
v0.2.6 is out 🎉  
https://github.com/yuyaban/gitlab-comment/releases/tag/v0.2.6

**Comment by kitagry** [comment]
Thank you！

**Pull request merged**
